---
title: 'Clean HOME data: Stimulation'
author: "Lucy King"
date: "2/6/2020"
output: html_document
---
```{r}
library(tidyverse)

home_cs_file <- "~/Box/lucy_king_files/BABIES/rsfMRI/data/language/HOME_cs_stimulation_cleaned_20200204.csv"
home_lg_file <- "~/Box/lucy_king_files/BABIES/rsfMRI/data/language/HOME_lg_stimulation_cleaned_20200204.csv"

```

Manual data cleaning:
In response to the number of different toys they had, mothers sometimes provided string values (e.g., a lot; too many to count) or ranges (e.g., 10-15). When a range was provided, took median value; if a range between only two numbers (e.g., 4-5), took lower number. If a qualitative description (e.g., too many to count), used highest reported value in that variable. 

# Read in data 
```{r}
home <-
  read_csv(home_cs_file) %>% 
  rename(ID = record_id) %>% 
  mutate(
    ID = as.numeric(ID),
    num_electoy = as.numeric(num_electoy)
  ) %>% 
  bind_rows(
    read_csv(home_lg_file)  %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.numeric(ID)) 
  )

glimpse(home)
```

```{r}
home_final <-
  home %>% 
  mutate(
    play_ppl = recode(
      play_ppl,
      "1" = "Mostly with caregiver",
      "2" = "Mostly with another child",
      "3" = "Mostly on his/her own"
    ),
    read_freq_chr = recode(
      read_freq,
      "6" = "Multiple times per day",
      "5" = "About once per day",
      "4" = "A few times a week",
      "3" = "About once per week",
      "2" = "Less than once a week",
      "1" = "Never"
    ),
    read_dur_chr = recode(
      read_dur,
      "1" = "1-2 minutes",
      "2" = "About 5 minutes",
      "3" = "About 10 minutes",
      "4" = "About 30 minutes",
      "5" = "Longer than 30 minutes"
    ),
    tvwatch_freq = if_else(
      tv_watch == 0,
      0, tvwatch_freq
    ),
    tvwatch_dur = if_else(
      tv_watch == 0,
      0, tvwatch_dur
    ),
    tvwatch_freq_chr = recode(
      tvwatch_freq,
      "6" = "Multiple times per day",
      "5" = "About once per day",
      "4" = "A few times a week",
      "3" = "About once per week",
      "2" = "Less than once a week",
      "1" = "Only on in the background",
      "0" = "Never"
    ),
    tvwatch_dur_chr = recode(
      tvwatch_dur,
      "1" = "Less than 10 minutes",
      "2" = "Between 10 and 30 minutes",
      "3" = "Between 30 and 60 minutes",
      "4" = "Between 1-2 hours",
      "5" = "Between 2-3 hours",
      "6" = "More than 3 hours",
      "0" = "None"
    ),
    play_smartphone = recode(
      play_smartphone,
      "1" = "Yes",
      "0" = "No",
      "2" = "Only for Facetime/Skype"
    ),
    play_smartphone_freq = if_else(
      play_smartphone == "No",
      0, play_smartphone_freq
    ),
    play_smartphone_dur = if_else(
      play_smartphone == "No",
      0, play_smartphone_dur
    ),
    play_smartphone_freq_chr = recode(
      play_smartphone_freq,
      "5" = "Multiple times a day",
      "4" = "About once a day",
      "3" = "A few times a week",
      "2" = "About once a week",
      "1" = "Less than once a week",
      "0" = "Never"
    ),
    play_smartphone_dur_chr = recode(
      play_smartphone_dur,
      "0" = "None",
      "1" = "1-2 minutes",
      "2" = "About 5 minutes",
      "3" = "About 10 minutes",
      "4" = "About 30 minutes",
      "5" = "Longer than 30 minutes",
    ),
    outside_freq = if_else(
      go_outside == 0,
      1, outside_freq
    ),
    outside_freq_chr = recode(
      outside_freq,
      "1" = "Never",
      "2" = "About once a week",
      "3" = "Two or three times a week",
      "4" = "Four to five times a week",
      "5" = "Six to seven days a week"
    )
  ) %>% 
  select(
    ID,
    redcap_event_name,
    play:read,
    read_freq, read_freq_chr,
    read_dur, read_dur_chr,
    num_books:tv_watch,
    tvwatch_freq, tvwatch_freq_chr,
    tvwatch_dur, tvwatch_dur_chr,
    play_smartphone,
    play_smartphone_freq, play_smartphone_freq_chr,
    play_smartphone_dur, play_smartphone_dur_chr,
    go_outside,
    outside_freq, outside_freq_chr,
    go_grocerystore:go_other_describe
  )
```

```{r}
write_csv(home, "~/Box/lucy_king_files/BABIES/rsfMRI/data/language/HOME_stimulation_cleaned_20200208.csv")
```

