---
title: "Score the Parental Empathy Measure (PEM)"
author: "Lucy King"
date: "1/22/2018"
output: html_document
---

# Set up environment
```{r}
#Libraries
library(tidyverse)

#Parameters
pem_cs_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/PEM/raw_data/pem_cs_complete.csv"
pem_long_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/PEM/raw_data/pem_lg_complete.csv"
```
# Read in data
```{r}
pem <-
  read_csv(pem_cs_file) %>% 
  rename(
    ID = record_id
  ) %>% 
  select(
    -redcap_event_name:-pem_timestamp,
    -pem_complete
  ) %>% 
  mutate(
    ID = as.integer(ID)
  ) %>% 
  bind_rows(
    read_csv(pem_long_file) %>% 
      rename(
        ID = record_id
      ) %>% 
      select(
        -redcap_event_name:-pem_timestamp,
        -pem_complete
      ) %>% 
      mutate(
        ID = as.numeric(ID)
      )
  )
```


# Score PEM
```{r}
pem <- 
  pem %>% 
  # reverse code items
  mutate_at(
    vars(
      pem_2, 
      pem_6, 
      pem_7, 
      pem_9,
      pem_10,
      pem_11,
      pem_12,
      pem_13,
      pem_15,
      pem_16,
      pem_18,
      pem_19,
      pem_25
    ),
    funs(
      . %>%
        recode("5" = 1, "4" = 2, "3" = 3, "2" = 4, "1" = 5)
    )
  )  %>%
  group_by(ID) %>% 
  # score cognitive empathy
  mutate(
    pem_cog_empath = mean(
      c(
        pem_1, 
        pem_6, 
        pem_17, 
        pem_12, 
        pem_8, 
        pem_10, 
        pem_4, 
        pem_15, 
        pem_20, 
        pem_7, 
        pem_23, 
        pem_13, 
        pem_24, 
        pem_2
      ),
      na.rm = TRUE
    ) * 14,
    # score affective empathy
    pem_aff_empath = mean(
      c(
        pem_5, 
        pem_13, 
        pem_14, 
        pem_18, 
        pem_21, 
        pem_9, 
        pem_3, 
        pem_19, 
        pem_22, 
        pem_16, 
        pem_25
      ),
      na.rm = TRUE
    ) * 11,
    # total score
    pem_total = mean(
      c(
        pem_1,
        pem_2, 
        pem_3, 
        pem_4, 
        pem_5, 
        pem_6, 
        pem_7,  
        pem_8,	
        pem_9, 	
        pem_10,	
        pem_11, 
        pem_12,	
        pem_13,	
        pem_14,	
        pem_15,	
        pem_16,	
        pem_17,	
        pem_18,	
        pem_19,	
        pem_20,	
        pem_21,	
        pem_22,	
        pem_23,	
        pem_24,	
        pem_25
      ),
      na.rm = TRUE
    ) * 25
  ) %>% 
  ungroup()

```

# Distributions
```{r}
pem %>% 
  ggplot(aes(pem_cog_empath)) +
  geom_histogram(binwidth = 2)

pem %>% 
  ggplot(aes(pem_aff_empath)) +
  geom_histogram(binwidth = 2)

pem %>% 
  ggplot(aes(pem_total)) +
  geom_histogram(binwidth = 5)
```

# Reliability
```{r}
pem %>% 
  select(
    pem_1, 
    pem_6, 
    pem_17, 
    pem_12, 
    pem_8, 
    pem_10, 
    pem_4, 
    pem_15, 
    pem_20, 
    pem_7, 
    pem_23, 
    pem_13, 
    pem_24, 
    pem_2
  ) %>% 
  psych::alpha()
```
```{r}
pem %>% 
  select(
    pem_5, 
    pem_13, 
    pem_14, 
    pem_18, 
    pem_21, 
    pem_9, 
    pem_3, 
    pem_19, 
    pem_22, 
    pem_16, 
    pem_25
  ) %>% 
  psych::alpha()
```

```{r}
pem %>% 
  select(
    pem_1,
    pem_2, 
    pem_3, 
    pem_4, 
    pem_5, 
    pem_6, 
    pem_7,  
    pem_8,	
    pem_9, 	
    pem_10,	
    pem_11, 
    pem_12,	
    pem_13,	
    pem_14,	
    pem_15,	
    pem_16,	
    pem_17,	
    pem_18,	
    pem_19,	
    pem_20,	
    pem_21,	
    pem_22,	
    pem_23,	
    pem_24,	
    pem_25
  ) %>% 
  psych::alpha()
```

```{r}
write_csv(
  pem, 
  "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/PEM/pem_scored_complete.csv"
)
```

