---
title: "Score CRISYS"
output: html_notebook
---

```{r}
#Libraries
library(tidyverse)
library(psych)
library(corrr)

#Paramaters
crisys_preg_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/CRISYS/raw_data/crisys_lg_preg_complete.csv"
crisys_nb_cs_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/CRISYS/raw_data/crisys_lg_nb_complete.csv"
crisys_6mo_lg_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/CRISYS/raw_data/crisys_lg_6mo_complete.csv"
crisys_6mo_cs_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/CRISYS/raw_data/crisys_cs_complete.csv"


#Functions
source("~/Desktop/BABIES/infant_scripts/babies_scoring/winsorize.R")

```

# Score crisys based on all items
```{r}
crisys <-
  read_csv(crisys_preg_file) %>% 
  rename(ID = record_id) %>% 
  mutate(ID = as.integer(ID)) %>% 
  select(-redcap_survey_identifier:-crisys_timestamp) %>% 
  bind_rows(
    read_csv(crisys_nb_cs_file) %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.integer(ID)) %>% 
      select(-redcap_survey_identifier:-crisys_timestamp)
  ) %>% 
  bind_rows(
    read_csv(crisys_6mo_cs_file) %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.integer(ID)) %>% 
      select(-redcap_survey_identifier:-crisys_timestamp) 
  ) %>% 
  bind_rows(
    read_csv(crisys_6mo_lg_file) %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.integer(ID)) %>% 
      select(-redcap_survey_identifier:-crisys_timestamp)
  ) %>% 
  filter(!is.na(crisys_1)) %>% 
  mutate(
    n_crisys = pmap_dbl(
        select(., c(crisys_1:crisys_72)),
        function(...) sum(!is.na(c(...)), na.rm = TRUE)
      ), 
    crisys_total = as.double(
      pmap_dbl(
        select(., c(crisys_1:crisys_72)),
        function(...) mean(c(...), na.rm = TRUE)
      ) * 72
    ) 
  ) %>% 
  rename(
    timepoint = redcap_event_name
  ) %>% 
  mutate(
    timepoint = if_else(
      timepoint == "questionnaires_6mo_arm_1",
      "sixmonth_arm_1", timepoint
    ),
    timepoint = str_remove(timepoint, "_arm_1")
  )

crisys <- 
  crisys %>% 
  group_by(timepoint) %>% 
  mutate(
    crisys_win = winsorize(crisys_total, product = 3)
  ) %>% 
  ungroup()
```

# Score crisys based on 60 items coded as objectively negative
```{r}
crisys_neg_vars <-
  crisys %>% 
  select(
    crisys_2,
    crisys_3,
    crisys_5:crisys_22,
    crisys_24,
    crisys_27:crisys_30,
    crisys_32:crisys_54,
    crisys_58:crisys_67,
    crisys_70:crisys_71
  ) %>% 
  names()


crisys <-
  crisys %>% 
  mutate(
    n_crisys_neg = pmap_dbl(
        select(., crisys_neg_vars),
        function(...) sum(!is.na(c(...)), na.rm = TRUE)
      ), 
    crisys_neg_total = as.double(
      pmap_dbl(
        select(., crisys_neg_vars),
        function(...) mean(c(...), na.rm = TRUE)
      ) * 60
    ) 
  )

crisys <- 
  crisys %>% 
  group_by(timepoint) %>% 
  mutate(
    crisys_neg_win = winsorize(crisys_neg_total, product = 3)
  ) %>% 
  ungroup()
```

# Score crisys based on negative SES items 

```{r}
crisys_ses_vars <-
  crisys %>% 
  select(
    crisys_2:crisys_12,
    crisys_66,
    crisys_70
  ) %>% 
  names()

crisys <-
  crisys %>% 
  mutate(
    n_crisys_ses = pmap_dbl(
        select(., crisys_ses_vars),
        function(...) sum(!is.na(c(...)), na.rm = TRUE)
      ), 
    crisys_ses_total = as.double(
      pmap_dbl(
        select(., crisys_ses_vars),
        function(...) mean(c(...), na.rm = TRUE)
      ) * 13
    ) 
  )

crisys <- 
  crisys %>% 
  group_by(timepoint) %>% 
  mutate(
    crisys_ses_win = winsorize(crisys_ses_total, product = 3)
  ) %>% 
  ungroup()
```

# Reliability

## Reliability for SES items
```{r}
crisys %>% 
  filter(timepoint == "pregnancy") %>% 
  select(
    crisys_ses_vars,
    #variables too missing to compute
    -crisys_9,
    -crisys_66,
    -crisys_70
  ) %>% 
  psych::alpha()

crisys %>% 
  filter(timepoint == "neonatal") %>% 
  select(
    crisys_ses_vars
  ) %>% 
  psych::alpha()

crisys %>% 
  filter(timepoint == "sixmonth") %>% 
  select(
    crisys_ses_vars
  ) %>% 
  psych::alpha()
```

## Reliability for negative items
```{r}
# pregnancy
crisys %>% 
  filter(timepoint == "pregnancy") %>% 
  select(
    crisys_2,
    crisys_3,
    crisys_5:crisys_22,
    crisys_24,
    crisys_27:crisys_30,
    crisys_32:crisys_54,
    crisys_58:crisys_67,
    crisys_70:crisys_71,
    #variables too missing to compute
    -crisys_9,
    -crisys_36,
    -crisys_42,
    -crisys_61,
    -crisys_24,
    -crisys_47,
    -crisys_52,
    -crisys_66,
    -crisys_70,
    -crisys_71
  ) %>% 
  psych::alpha()

# newborn
crisys %>% 
  filter(timepoint == "neonatal") %>% 
  select(
    crisys_2,
    crisys_3,
    crisys_5:crisys_22,
    crisys_24,
    crisys_27:crisys_30,
    crisys_32:crisys_54,
    crisys_58:crisys_67,
    crisys_70:crisys_71,
    #variables too missing to compute
    -crisys_11,
    -crisys_12,
    -crisys_24,
    -crisys_36,
    -crisys_37,
    -crisys_40,
    -crisys_41,
    -crisys_46,
    -crisys_47,
    -crisys_20,
    -crisys_50,
    -crisys_70,
    -crisys_71
  ) %>% 
  psych::alpha()


# 6 months
crisys %>% 
  filter(timepoint == "sixmonth") %>% 
  select(
    crisys_2,
    crisys_3,
    crisys_5:crisys_22,
    crisys_24,
    crisys_27:crisys_30,
    crisys_32:crisys_54,
    crisys_58:crisys_67,
    crisys_70:crisys_71,
    #variables too missing to compute
    -crisys_46,
    -crisys_47,
    -crisys_70,
    -crisys_71
  ) %>% 
  psych::alpha()
```

## Reliability for all items
```{r}
# pregnancy
crisys %>% 
  filter(timepoint == "pregnancy") %>% 
  select(
    crisys_1:crisys_72,
    -crisys_9,
    -crisys_36,
    -crisys_42,
    -crisys_61,
    -crisys_24,
    -crisys_47,
    -crisys_52,
    -crisys_66,
    -crisys_70,
    -crisys_71,
    -crisys_68,
    -crisys_69
  ) %>% 
  psych::alpha()

# newborn
crisys %>% 
  filter(timepoint == "neonatal") %>% 
  select(
    crisys_1:crisys_72,
    #variables too missing to compute
    -crisys_11,
    -crisys_12,
    -crisys_24,
    -crisys_36,
    -crisys_37,
    -crisys_40,
    -crisys_41,
    -crisys_46,
    -crisys_47,
    -crisys_20,
    -crisys_50,
    -crisys_70,
    -crisys_71,
    -crisys_68,
    -crisys_69
  ) %>% 
  psych::alpha()


# 6 months
crisys %>% 
  filter(timepoint == "sixmonth") %>% 
  select(
    crisys_1:crisys_72,
    #variables too missing to compute
    -crisys_46,
    -crisys_47,
    -crisys_70,
    -crisys_71,
    -crisys_69,
    -crisys_24
  ) %>% 
  psych::alpha()
```
# Tidy data
```{r}
crisys <-
  crisys %>% 
  mutate(
    timepoint = case_when(
      timepoint == "pregnancy" ~ "T1",
      timepoint == "neonatal" ~ "T2",
      timepoint == "sixmonth" ~ "T3"
    )
  )

crisys_wf <-
  crisys %>% 
  pivot_wider(
    names_from = timepoint,
    values_from = crisys_1:last_col()
  )

crisys_6mo <-
  crisys %>% 
  filter(timepoint == "T3")
```

# Histograms

## total score
```{r}
crisys %>% 
  ggplot(aes(timepoint, crisys_total)) +
  geom_line(
    aes(
      timepoint, 
      crisys_total, 
      group = ID
    ),
    color = "blue",
    alpha = 1/4
  ) +
  theme(
    legend.position = "none"
  )

crisys %>% 
  ggplot(aes(timepoint, crisys_total)) +
  geom_boxplot()

crisys %>% 
  ggplot(aes(crisys_total)) +
  geom_histogram() +
  facet_wrap(~timepoint)

crisys %>% 
  ggplot(aes(crisys_win)) +
  geom_histogram() +
  facet_wrap(~timepoint)
```
## ses score
```{r}
crisys %>% 
  ggplot(aes(timepoint, crisys_ses_total)) +
  geom_line(
    aes(
      timepoint, 
      crisys_ses_total, 
      group = ID
    ),
    color = "blue",
    alpha = 1/4
  ) +
  theme(
    legend.position = "none"
  )

crisys %>% 
  ggplot(aes(timepoint, crisys_ses_total)) +
  geom_boxplot()

crisys %>% 
  ggplot(aes(crisys_ses_total)) +
  geom_histogram() +
  facet_wrap(~timepoint)
```



```{r}
write_csv(crisys_wf, "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/CRISYS/crisys_scored_wf_complete.csv")

write_csv(crisys, "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/CRISYS/crisys_scored_lf_complete.csv")

write_csv(crisys_6mo, "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/CRISYS/crisys_scored_6mo_complete.csv")

glimpse(crisys_wf)
```


