---
title: "Score the Attachment Style Questionnaire"
author: "Lucy King"
date: "11/05/2019"
output: html_document
---

```{r}
#Libraries
library(tidyverse)
library(psych)

#Files
asq_cs_file <- "~/Desktop/BABIES/data/mom_attachment_cs_20191105.csv"
asq_lg_file <- "~/Desktop/BABIES/data/mom_attachment_lg_20191105.csv"

source("identify_outliers_histogram.R")
```

# Read in data
```{r}
asq <-
  read_csv(att_cs_file) %>% 
  select(
    -redcap_survey_identifier,
    -attachment_style_q_timestamp
  ) %>% 
  bind_rows(
    read_csv(att_lg_file)
  ) %>% 
  select(
    -redcap_survey_identifier,
    -attachment_style_q_timestamp
  ) %>% 
  rename(ID = record_id) %>% 
  filter(attachment_style_q_complete == 2) %>% 
  select(-attachment_style_q_complete)
```

# Score 
```{r}
# reverse code
asq <-
  asq %>% 
  mutate_at(
    vars(asq_20, asq_21, asq_33),
    funs(
      "r" =
        . %>% 
        recode("1" = 6, "2" = 5, "3" = 4, "4" = 3, "5" = 2, "6" = 1)
    )
  ) %>% 
  mutate_at(
    vars(asq_1:asq_33_r),
    funs(
      . %>%
        recode("1" = 0, "2" = 1, "3" = 2, "4" = 3, "5" = 4, "6" = 5)
    )
  ) %>% 
  group_by(ID) %>% 
  mutate(
    #confidence
    asq_conf = mean(
      c(asq_1, asq_2, asq_3, asq_19, asq_31, asq_33_r, asq_37, asq_38),
      na.rm = TRUE
    ) * 8,
    #discomfort with relationships
    asq_discomf = mean(
      c(asq_4, asq_5, asq_16, asq_17, asq_20_r, asq_21_r, asq_23, asq_25, asq_26, asq_3),
      na.rm = TRUE
    ) * 10,
    #relationships are secondary
    asq_second = mean(
      c(asq_6, asq_7, asq_8, asq_9, asq_10, asq_14, asq_36),
      na.rm = TRUE
    ) * 7,
    #need for approval
    asq_approv = mean(
      c(asq_11, asq_12, asq_13, asq_15, asq_24, asq_27, asq_35),
      na.rm = TRUE
    ) * 7,
    #preoccupation with relationships
    asq_preocc = mean(
      c(asq_18, asq_22, asq_28, asq_29, asq_30, asq_32, asq_39, asq_40),
      na.rm = TRUE
    ) * 8,
    asq_total = asq_conf + asq_discomf + asq_second + asq_approv + asq_preocc
  ) %>% 
  ungroup()
```

# Visualize
```{r}
identify_outliers_hist(asq, asq_conf)
identify_outliers_hist(asq, asq_discomf)
identify_outliers_hist(asq, asq_second)
identify_outliers_hist(asq, asq_approv)
identify_outliers_hist(asq, asq_preocc)
identify_outliers_hist(asq, asq_total)
```

# Reliability
```{r}
# confidence 
asq %>% 
  select(asq_1, asq_2, asq_3, asq_19, asq_31, asq_33_r, asq_37, asq_38) %>% 
  alpha()
 
# discomfort wit relationships  
asq %>% 
  select(asq_4, asq_5, asq_16, asq_17, asq_20_r, asq_21_r, asq_23, asq_25, asq_26, asq_3) %>% 
  alpha()

#relationships are secondary
asq %>% 
  select(asq_6, asq_7, asq_8, asq_9, asq_10, asq_14, asq_36) %>% 
  alpha()

#need for approval
asq %>% 
  select(asq_11, asq_12, asq_13, asq_15, asq_24, asq_27, asq_35) %>% 
  alpha()

#preoccupation with relationships
asq %>% 
  select(asq_18, asq_22, asq_28, asq_29, asq_30, asq_32, asq_39, asq_40) %>% 
  alpha()

#total
asq %>% 
  select(asq_1:asq_19, asq_20_r, asq_21_r, asq_22:asq_32, asq_33_r, asq_34:asq_40) %>% 
  alpha()
```
