---
title: "Score EPDS"
output: html_notebook
---

```{r}
#Libraries
library(tidyverse)

#Parameters
epds_cs_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/EPDS/raw_data/epds_cs_complete.csv"
epds_lg_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/EPDS/raw_data/epds_lg_complete.csv"
```

# Read in and score data
```{r}
epds_cs <-
  read_csv(epds_cs_file) %>%
  rename(ID = record_id) %>%
  mutate(
    ID = as.integer(ID),
    redcap_event_name = "T3"
  ) %>% 
  dplyr::select(
    -redcap_survey_identifier:-epds_timestamp,
    -epds_complete
  ) %>%
  mutate_at(
    vars(epds_1:epds_10),
    as.numeric
  ) %>% 
  mutate_at(
    vars(
      epds_3,
      epds_5:epds_10
    ),
    funs(
      . %>%
        dplyr::recode(
          "3" = 0,
          "2" = 1,
          "1" = 2,
          "0" = 3
        )
    )
  ) %>% 
  group_by(ID) %>% 
  mutate(
    epds_total = mean(
      c(
        epds_1, 
        epds_2, 
        epds_3, 
        epds_4, 
        epds_5, 
        epds_6, 
        epds_7,
        epds_8,
        epds_9,
        epds_10
      ),
      na.rm = TRUE
    ) * 10,
    epds_3A = mean( #anxiety items
      c(
        epds_3,
        epds_4,
        epds_5
      ),
      na.rm = TRUE
    ) * 3
  ) %>% 
  ungroup()
```

```{r}
epds_lg <-
  read_csv(epds_lg_file) %>%
  rename(ID = record_id) %>%
  mutate(
    ID = as.integer(ID),
    redcap_event_name = dplyr::recode(
      redcap_event_name,
      "pregnancy_arm_1" = "T1",
      "neonatal_arm_1" = "T2",
      "sixmonth_arm_1" = "T3"
    )
  ) %>% 
  dplyr::select(
    -redcap_survey_identifier:-epds_timestamp,
    -epds_complete
  ) %>%
  mutate_at(
    vars(epds_1:epds_10),
    as.numeric
  ) %>% 
  mutate_at(
    vars(
      epds_3,
      epds_5:epds_10
    ),
    funs(
      . %>%
        dplyr::recode(
          "3" = 0,
          "2" = 1,
          "1" = 2,
          "0" = 3
        )
    )
  ) %>% 
  group_by(ID, redcap_event_name) %>% 
  mutate(
    epds_total = mean(
      c(
        epds_1, 
        epds_2, 
        epds_3, 
        epds_4, 
        epds_5, 
        epds_6, 
        epds_7,
        epds_8,
        epds_9,
        epds_10
      ),
      na.rm = TRUE
    ) * 10,
    epds_3A = mean( #anxiety items
      c(
        epds_3,
        epds_4,
        epds_5
      ),
      na.rm = TRUE
    ) * 3
  ) %>% 
  ungroup()
```

```{r}
epds_lf <-
  epds_cs %>% 
  bind_rows(epds_lg) %>% 
  rename(
    timepoint = redcap_event_name
  )
```

```{r}
epds_wf <-
  epds_lf %>% 
  dplyr::select(ID, timepoint, epds_total, epds_3A) %>% 
  pivot_wider(
    names_from = timepoint,
    values_from = c(epds_total, epds_3A)
  ) %>% 
  rename_at(
    vars(-ID),
    funs(str_to_lower(.))
  ) %>% 
  mutate(
    epds_t1_concern = if_else(
      epds_total_t1 > 10, "clinical concern", "none"
    ),
    epds_t2_concern = if_else(
      epds_total_t2 > 10, "clinical concern", "none"
    ),
    epds_t3_concern = if_else(
      epds_total_t3 > 10, "clinical concern", "none"
    )
  ) %>% 
  group_by(ID) %>% 
  mutate(
    max_epds_t1t2 = max(c(epds_total_t1, epds_total_t2), na.rm = TRUE),
    max_epds_t1t2 = if_else(max_epds_t1t2 == -Inf, NA_real_, max_epds_t1t2)
  ) %>% 
  ungroup()
```

# Reliability
```{r}
epds_lf %>% 
  filter(timepoint == "T1") %>% 
  dplyr::select(epds_1:epds_10) %>% 
  psych::alpha()

epds_lf %>% 
  filter(timepoint == "T2") %>% 
  dplyr::select(epds_1:epds_10) %>% 
  psych::alpha()

epds_lf %>% 
  filter(timepoint == "T3") %>% 
  dplyr::select(epds_1:epds_10) %>% 
  psych::alpha()
```

# Distributions
```{r}
epds_lf %>% 
  ggplot(aes(epds_total, fill = timepoint)) +
  geom_density(alpha = 1/2)

epds_wf %>% 
  ggplot(aes(max_epds_t1t2)) +
  geom_histogram()
```

```{r}
write_csv(epds_lf, "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/EPDS/epds_lf_complete.csv")

write_csv(epds_wf, "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/EPDS/epds_wf_complete.csv")
```

