---
title: "Score MBCDI"
author: "Lucy King"
date: "2/10/2020"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)

demo_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/demographics/dob_sex_race_final.csv"
cs_18_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/survey_18month/raw_data/mo18_survey_cs_complete.csv"
lg_18_file <- "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/survey_18month/raw_data/mo18_survey_lg_20201229.csv"
```

# Read in data
```{r}
demo <-
  read_csv(demo_file) %>% 
  dplyr::select(
    ID,
    male,
    baby_dob
  )
```

```{r}
m_cs <-
  read_csv(cs_18_file) %>% 
  dplyr::select(
    ID = record_id,
    date_18mo_survey = questionnaires_18mo_timestamp,
    age_first_word = aofp_1,
    primarylang_18mo:secondlang_18mo_type,
    mbcdi_1___1:mbcdi_101
  ) %>% 
  mutate(
    ID = as.numeric(ID),
    date_18mo_survey = parse_date_time2(date_18mo_survey, "mdy HM")
  )
```

```{r}
m_lg <-
  read_csv(lg_18_file) %>% 
  mutate(
    date_18mo_survey = parse_date_time2(month_survey_timestamp, "mdy HM")
  ) %>% 
  rename(ID = record_id)
```

```{r}
m <-
  m_cs %>% 
  bind_rows(m_lg)
```

```{r}
m <-
  m %>% 
  dplyr::select(
    ID,
    date_18mo_survey,
    age_first_word = aofp_1,
    primarylang_18mo:secondlang_18mo_type,
    mbcdi_1___1:mbcdi_101
  ) %>%  
  left_join(demo, by = "ID") %>% 
  mutate(
    age_18mo = (baby_dob %--% date_18mo_survey) / months(1),
    primary_english = case_when(
      primarylang_18mo == "English" | primarylang_18mo == "english" ~ 1,
      primarylang_18mo != "English" & primarylang_18mo != "english" ~ 0,
      TRUE ~ NA_real_
    )
  ) %>% 
  filter(ID != 1)
```


```{r}
m %>% 
  summarise_at(
    vars(age_18mo),
    funs(mean, sd, min, max), na.rm = TRUE
  )
```

# Clean data

Recode "understands" responses so == 1 if "understands and says" endorsed.

```{r}
understands_vars <-
  m %>% 
  dplyr::select(ends_with("___1")) %>% 
  names()

says_vars <-
  m %>% 
  dplyr::select(ends_with("___2")) %>% 
  names()
```

```{r}
# Recode "understands" variables so that = 1 if selected "understands" but did not select "understands and says" and so that = 0 if selected both "understands" and "understands and says" or only "understands and says". Therefore, values = 1 for understands variables always indicate that the child ONLY understands and does not say.

m <-
  m %>% 
  mutate_at(
    all_of(understands_vars),
    funs(
      if_else(
        get(str_replace(quote(.), "___1", "___2")) == 1,
        1, .
      )
    )
  )
```

# Score
```{r}
m <-
  m %>% 
  mutate(
    mbcdi_understand_tot = pmap_dbl(
      dplyr::select(., understands_vars),
      function(...) sum(c(...), na.rm = TRUE)
    ),
    mbcdi_says_tot = pmap_dbl(
      dplyr::select(., says_vars),
      function(...) sum(c(...), na.rm = TRUE)
    ),
    mbcdi_says_percentile = case_when(
      # female norms, 18 months
      male == 0 & round(age_18mo) == 18 & (mbcdi_says_tot > 74) ~ 99,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 57 & mbcdi_says_tot <= 74) ~ 95,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 54 & mbcdi_says_tot <= 57) ~ 90,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 43 & mbcdi_says_tot <= 54) ~ 85,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 40 & mbcdi_says_tot <= 43) ~ 80,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 38 & mbcdi_says_tot <= 40) ~ 65,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 36 & mbcdi_says_tot <= 38) ~ 60,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 33 & mbcdi_says_tot <= 36) ~ 55,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 30 & mbcdi_says_tot <= 33) ~ 50,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 28 & mbcdi_says_tot <= 30) ~ 45,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 26 & mbcdi_says_tot <= 28) ~ 40,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 24 & mbcdi_says_tot <= 26) ~ 35,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 23 & mbcdi_says_tot <= 24) ~ 30,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 20 & mbcdi_says_tot <= 23) ~ 25,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 19 & mbcdi_says_tot <= 20) ~ 20,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 17 & mbcdi_says_tot <= 19) ~ 15,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 13 & mbcdi_says_tot <= 17) ~ 10,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot <= 13) ~ 5,
      # female norms, 19 months
      male == 0 & round(age_18mo) == 19 & (mbcdi_says_tot > 80) ~ 99,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 66 & mbcdi_says_tot <= 80) ~ 95,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 62 & mbcdi_says_tot <= 66) ~ 90,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 51 & mbcdi_says_tot <= 62) ~ 85,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 50 & mbcdi_says_tot <= 51) ~ 80,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 46 & mbcdi_says_tot <= 50) ~ 70,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 44 & mbcdi_says_tot <= 46) ~ 65,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 42 & mbcdi_says_tot <= 44) ~ 60,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 39 & mbcdi_says_tot <= 42) ~ 55,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 35 & mbcdi_says_tot <= 39) ~ 50,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 34 & mbcdi_says_tot <= 35) ~ 45,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 31 & mbcdi_says_tot <= 34) ~ 40,
      male == 0 & round(age_18mo) == 18 & 
        (mbcdi_says_tot > 29 & mbcdi_says_tot <= 31) ~ 35,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 27 & mbcdi_says_tot <= 29) ~ 30,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 24 & mbcdi_says_tot <= 27) ~ 25,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 22 & mbcdi_says_tot <= 24) ~ 20,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 20 & mbcdi_says_tot <= 22) ~ 15,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot > 15 & mbcdi_says_tot <= 20) ~ 7,
      male == 0 & round(age_18mo) == 19 & 
        (mbcdi_says_tot <= 15) ~ 5,
      # female norms, 20 months
      male == 0 & round(age_18mo) == 20 & (mbcdi_says_tot > 85) ~ 99,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 74 & mbcdi_says_tot <= 85) ~ 95,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 70 & mbcdi_says_tot <= 74) ~ 90,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 59 & mbcdi_says_tot <= 70) ~ 85,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 57 & mbcdi_says_tot <= 59) ~ 80,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 52 & mbcdi_says_tot <= 57) ~ 70,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 50 & mbcdi_says_tot <= 52) ~ 65,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 48 & mbcdi_says_tot <= 50) ~ 60,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 45 & mbcdi_says_tot <= 48) ~ 55,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 41 & mbcdi_says_tot <= 45) ~ 50,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 40 & mbcdi_says_tot <= 41) ~ 45,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 37 & mbcdi_says_tot <= 40) ~ 40,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 34 & mbcdi_says_tot <= 37) ~ 35,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 33 & mbcdi_says_tot <= 34) ~ 30,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 28 & mbcdi_says_tot <= 33) ~ 25,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 26 & mbcdi_says_tot <= 28) ~ 20,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 23 & mbcdi_says_tot <= 26) ~ 15,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot > 17 & mbcdi_says_tot <= 23) ~ 20,
      male == 0 & round(age_18mo) == 20 & 
        (mbcdi_says_tot <= 17) ~ 5,
      # male norms, 18 months
      male == 1 & round(age_18mo) == 18 & (mbcdi_says_tot >= 77) ~ 99,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 74 & mbcdi_says_tot < 77) ~ 95,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 53 & mbcdi_says_tot < 74) ~ 90,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 46 & mbcdi_says_tot < 53) ~ 85,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 41 & mbcdi_says_tot < 46) ~ 80,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 37 & mbcdi_says_tot < 41) ~ 75,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 34 & mbcdi_says_tot < 38) ~ 70,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 30 & mbcdi_says_tot < 34) ~ 65,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 28 & mbcdi_says_tot < 30) ~ 60,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 24 & mbcdi_says_tot < 28) ~ 55,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 23 & mbcdi_says_tot < 24) ~ 50,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 18 & mbcdi_says_tot < 23) ~ 45,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 17 & mbcdi_says_tot < 18) ~ 40,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 16 & mbcdi_says_tot < 17) ~ 35,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 15 & mbcdi_says_tot < 16) ~ 30,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 14 & mbcdi_says_tot < 15) ~ 25,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 12 & mbcdi_says_tot < 14) ~ 20,
       male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 10 & mbcdi_says_tot < 12) ~ 15,
       male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 9 & mbcdi_says_tot < 10) ~ 10,
       male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 4 & mbcdi_says_tot < 9) ~ 5,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot < 4) ~ 0,
      # male norms, 19 months
      male == 1 & round(age_18mo) == 19 & (mbcdi_says_tot >= 83) ~ 99,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >=81 & mbcdi_says_tot < 83) ~ 95,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 61 & mbcdi_says_tot < 81) ~ 90,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 52 & mbcdi_says_tot < 61) ~ 85,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 47 & mbcdi_says_tot < 52) ~ 80,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 43 & mbcdi_says_tot < 47) ~ 75,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 39 & mbcdi_says_tot < 43) ~ 70,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 35 & mbcdi_says_tot < 39) ~ 65,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 33 & mbcdi_says_tot < 35) ~ 60,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 29 & mbcdi_says_tot < 33) ~ 55,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 25 & mbcdi_says_tot < 29) ~ 50,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 22 & mbcdi_says_tot < 25) ~ 45,
      male == 1 & round(age_18mo) == 18 & 
        (mbcdi_says_tot >= 20 & mbcdi_says_tot < 22) ~ 40,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 19 & mbcdi_says_tot < 20) ~ 35,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 18 & mbcdi_says_tot < 19) ~ 30,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 17 & mbcdi_says_tot < 18) ~ 25,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 15 & mbcdi_says_tot < 17) ~ 20,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 12 & mbcdi_says_tot < 15) ~ 15,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 11 & mbcdi_says_tot < 12) ~ 10,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot >= 5 & mbcdi_says_tot < 11) ~ 5,
      male == 1 & round(age_18mo) == 19 & 
        (mbcdi_says_tot < 5) ~ 0,
      # male norms, 20 months
      male == 1 & round(age_18mo) == 20 & (mbcdi_says_tot >= 87) ~ 99,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 86 & mbcdi_says_tot < 87) ~ 95,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 69 & mbcdi_says_tot < 86) ~ 90,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 59 & mbcdi_says_tot < 69) ~ 85,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 53 & mbcdi_says_tot < 59) ~ 80,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 49 & mbcdi_says_tot < 53) ~ 75,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 45 & mbcdi_says_tot < 49) ~ 70,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 40 & mbcdi_says_tot < 45) ~ 65,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 37 & mbcdi_says_tot < 40) ~ 60,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 33 & mbcdi_says_tot < 37) ~ 55,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 30 & mbcdi_says_tot < 33) ~ 50,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 27 & mbcdi_says_tot < 30) ~ 45,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 25 & mbcdi_says_tot < 27) ~ 40,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 23 & mbcdi_says_tot < 25) ~ 35,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 22 & mbcdi_says_tot < 23) ~ 30,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 20 & mbcdi_says_tot < 22) ~ 25,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 18 & mbcdi_says_tot < 20) ~ 20,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 14 & mbcdi_says_tot < 18) ~ 15,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 13 & mbcdi_says_tot < 14) ~ 10,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot >= 6 & mbcdi_says_tot < 13) ~ 5,
      male == 1 & round(age_18mo) == 20 & 
        (mbcdi_says_tot < 6) ~ 0
    )
  ) 
```

# Reliability
```{r}
m %>% 
  dplyr::select(
    understands_vars
  ) %>% 
  psych::alpha()

m %>% 
  dplyr::select(
    says_vars
  ) %>% 
  psych::alpha()
```

# Visualize
```{r}
m %>% 
  ggplot(aes(age_18mo)) +
  geom_histogram()

m %>% 
  ggplot(aes(mbcdi_understand_tot)) +
  geom_histogram()

m %>% 
  ggplot(aes(mbcdi_says_tot)) +
  geom_histogram()

m %>% 
  ggplot(aes(mbcdi_says_percentile)) +
  geom_histogram()

m %>% 
  ggplot(aes(mbcdi_says_percentile, fill = factor(male))) +
  geom_density(alpha = 1/2)
```

```{r}
m %>% 
  filter(age_18mo < 21) %>% 
  ggplot(aes(age_18mo, mbcdi_understand_tot)) +
  geom_point() +
  geom_smooth(method = "gam")

cor.test(m$age_18mo, m$mbcdi_understand_tot, method = "spearman")

m %>% 
  ggplot(aes(age_18mo, mbcdi_says_tot)) +
  geom_point() +
  geom_smooth(method = "gam")

cor.test(m$age_18mo, m$mbcdi_says_tot, method = "spearman")

m %>% 
  ggplot(aes(age_18mo, mbcdi_says_percentile)) +
  geom_point() +
  geom_smooth(method = "gam")

cor.test(m$age_18mo, m$mbcdi_says_percentile, method = "spearman")
```

```{r}
m %>% 
  filter(!is.na(male)) %>% 
  ggplot(aes(factor(male), mbcdi_understand_tot)) +
  geom_boxplot()

t.test(m$mbcdi_understand_tot ~ m$male)

m %>% 
  filter(!is.na(male)) %>% 
  ggplot(aes(factor(male), mbcdi_says_tot)) +
  geom_boxplot()

t.test(m$mbcdi_says_tot ~ m$male)

m %>% 
  filter(!is.na(male)) %>% 
  ggplot(aes(factor(male), mbcdi_says_percentile)) +
  geom_boxplot()

t.test(m$mbcdi_says_percentile ~ m$male)
```

```{r}
m %>% 
  filter(!is.na(primary_english)) %>% 
  ggplot(aes(factor(primary_english), mbcdi_understand_tot)) +
  geom_boxplot()

t.test(m$mbcdi_understand_tot ~ m$primary_english)

m %>% 
  filter(!is.na(primary_english)) %>% 
  ggplot(aes(factor(primary_english), mbcdi_says_tot)) +
  geom_boxplot()

t.test(m$mbcdi_says_tot ~ m$primary_english)

m %>% 
  filter(!is.na(primary_english)) %>% 
  ggplot(aes(factor(primary_english), mbcdi_says_percentile)) +
  geom_boxplot()

t.test(m$mbcdi_says_percentile ~ m$primary_english)
```

```{r}
mbcdi_scored <-
  m %>% 
  dplyr::select(
    ID,
    age_18mo,
    male,
    primary_english,
    primarylang_18mo,
    mbcdi_understand_tot,
    mbcdi_says_tot,
    mbcdi_says_percentile
  )

write_csv(mbcdi_scored, "~/Box/Mooddata_Coordinating/BABIES/Data/final_scored_data/survey_18month/mbcdi_scored_20210315.csv")
```

