---
title: "Score the MNBS"
output: html_document
---

```{r}
#Libraries
library(tidyverse)

#Parameters
mnbs_6mo_file <- "~/Desktop/BABIES/neglect_perspective/data/BABIES6Months_mnbs_20180916.csv"
mnbs_long_file <- "~/Desktop/BABIES/neglect_perspective/data/LongitudinalBABIES_mnbs_20180916.csv"
```

```{r}
mnbs <-
  read_csv(mnbs_6mo_file) %>% 
  select(
    -redcap_event_name:-mnbs_timestamp,
    -mnbs_complete
  ) %>% 
  rename(ID = record_id) %>% 
  mutate(ID = as.integer(ID)) %>% 
  bind_rows(
    read_csv(mnbs_long_file) %>% 
      select(
        -redcap_event_name:-mnbs_timestamp,
        -mnbs_complete
      ) %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.integer(ID)) 
  )
```

```{r}
mnbs <- 
  mnbs %>% 
  mutate_at(
    vars(
      mnbs_2:mnbs_9
    ),
    funs(
      . %>%
        recode(
          "4" = 3,
          "3" = 2,
          "2" = 1,
          "1" = 0
        )
    )
  ) %>% 
  group_by(ID) %>% 
  mutate(
    mnbs_total = mean(
      c(
        mnbs_2,
        mnbs_3,
        mnbs_4,
        mnbs_5,
        mnbs_6,
        mnbs_7,
        mnbs_8,
        mnbs_9
      ),
      na.rm = TRUE
    ) * 8,
    mnbs_cognitive = mean(
      c(
        mnbs_2,
        mnbs_3
      ),
      na.rm = TRUE
    ) * 2,
    mnbs_supervisory = mean(
      c(
        mnbs_4,
        mnbs_5
      ),
      na.rm = TRUE
    ) * 2,
    mnbs_emotional = mean(
      c(
        mnbs_6,
        mnbs_7
      ),
      na.rm = TRUE
    ) * 2,
    mnbs_physical = mean(
      c(
        mnbs_8,
        mnbs_9
      ),
      na.rm = TRUE
    ) * 2 
  ) %>% 
  ungroup()
  
```

